[build]
  # Build command for Vite
  command = "npm run build"

  # Directory where the built files will be located
  publish = "dist"

[build.environment]
  # Node.js version for the build environment
  NODE_VERSION = "18"

[[redirects]]
  # Redirect all API calls to the backend (this would need to be updated with your actual backend URL)
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200

[functions]
  # If you had serverless functions, they would go here
  # directory = "netlify/functions"
